/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


DROP DATABASE IF EXISTS `control_tiempo`;
CREATE DATABASE `control_tiempo` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `control_tiempo`;
DROP TABLE IF EXISTS `day`;
CREATE TABLE `day` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DAY` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `intervals`;
CREATE TABLE `intervals` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TASK_ID` int(11) DEFAULT NULL,
  `TIME_START` time DEFAULT NULL,
  `TIME_END` time DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `task_id` (`TASK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `task`;
CREATE TABLE `task` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DAY_ID` int(11) DEFAULT NULL,
  `TITLE` longtext DEFAULT NULL,
  `DESCRIPTION` longtext DEFAULT NULL,
  `APPLICANT` longtext DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
