/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


DROP DATABASE IF EXISTS `control_tiempo`;
CREATE DATABASE `control_tiempo` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `control_tiempo`;
DROP TABLE IF EXISTS `day`;
CREATE TABLE `day` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DAY` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `intervals`;
CREATE TABLE `intervals` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TASK_ID` int(11) DEFAULT NULL,
  `TIME_START` time DEFAULT NULL,
  `TIME_END` time DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `task_id` (`TASK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=977 DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `task`;
CREATE TABLE `task` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `DAY_ID` int(11) DEFAULT NULL,
  `TITLE` longtext DEFAULT NULL,
  `DESCRIPTION` longtext DEFAULT NULL,
  `APPLICANT` longtext DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `JOINED` char(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `task_USUARIO_ID_user_ID` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=707 DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(256) DEFAULT NULL,
  `PASSWORD` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

ALTER TABLE `task`
ADD CONSTRAINT `task_USUARIO_ID_user_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`);


/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
